"""add username gender birth columns

Revision ID: 17ce6d9cbdb1
Revises: e01f1cde63ae
Create Date: 2026-01-16 11:00:41.393949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17ce6d9cbdb1'
down_revision: Union[str, Sequence[str], None] = 'e01f1cde63ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(), nullable=False))
    op.add_column('users', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('users', sa.Column('birth', sa.Date(), nullable=True))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'birth')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
