"""create_music_info_tables

Revision ID: 3755752e0e67
Revises: 75f30d693225
Create Date: 2026-02-03 16:34:40.076809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3755752e0e67'
down_revision: Union[str, Sequence[str], None] = '75f30d693225'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('musics',
    sa.Column('music_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('spotify_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('artist', sa.String(length=100), nullable=False),
    sa.Column('album_cover', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('music_id')
    )
    op.create_index(op.f('ix_musics_music_id'), 'musics', ['music_id'], unique=False)
    op.create_index(op.f('ix_musics_spotify_id'), 'musics', ['spotify_id'], unique=True)
    op.create_table('music_diaries',
    sa.Column('diary_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('music_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('weather', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('mood', sa.String(length=50), nullable=True),
    sa.Column('situation', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['music_id'], ['musics.music_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('diary_id')
    )
    op.create_index(op.f('ix_music_diaries_diary_id'), 'music_diaries', ['diary_id'], unique=False)
    op.create_table('playlists',
    sa.Column('playlist_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('original_playlist_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('weather', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('mood', sa.String(length=50), nullable=True),
    sa.Column('situation', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['original_playlist_id'], ['playlists.playlist_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('playlist_id')
    )
    op.create_index(op.f('ix_playlists_playlist_id'), 'playlists', ['playlist_id'], unique=False)
    op.create_table('playlists_tracks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('playlist_id', sa.BigInteger(), nullable=False),
    sa.Column('music_id', sa.BigInteger(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['music_id'], ['musics.music_id'], ),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.playlist_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playlists_tracks_id'), 'playlists_tracks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_playlists_tracks_id'), table_name='playlists_tracks')
    op.drop_table('playlists_tracks')
    op.drop_index(op.f('ix_playlists_playlist_id'), table_name='playlists')
    op.drop_table('playlists')
    op.drop_index(op.f('ix_music_diaries_diary_id'), table_name='music_diaries')
    op.drop_table('music_diaries')
    op.drop_index(op.f('ix_musics_spotify_id'), table_name='musics')
    op.drop_index(op.f('ix_musics_music_id'), table_name='musics')
    op.drop_table('musics')
    # ### end Alembic commands ###
