"""Create : userdata table


Revision ID: 3d8ae5b12268
Revises: 17ce6d9cbdb1
Create Date: 2026-01-31 00:15:58.173177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d8ae5b12268'
down_revision: Union[str, Sequence[str], None] = '17ce6d9cbdb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_preferred_artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('spotify_artist_id', sa.String(), nullable=False),
    sa.Column('artist_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_preferred_artists_id'), 'user_preferred_artists', ['id'], unique=False)
    op.create_table('user_preferred_genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('genre_code', sa.String(), nullable=False),
    sa.Column('genre_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_preferred_genres_id'), 'user_preferred_genres', ['id'], unique=False)
    op.alter_column('users', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'birth',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'birth',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('users', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_user_preferred_genres_id'), table_name='user_preferred_genres')
    op.drop_table('user_preferred_genres')
    op.drop_index(op.f('ix_user_preferred_artists_id'), table_name='user_preferred_artists')
    op.drop_table('user_preferred_artists')
    # ### end Alembic commands ###
